### ISSUE TITLE
Is there a way to restore my notes from my backup?

### ISSUE THREAD

**Issue by ChandelierX** [JulienPalard/turtl-backup#3]
While, I think backup is meaningful when users could restore from their backup.
I'm new to turtl. I've already setup my own turtl server, and finished backup from my client.
I wonder how can I use this backup? To put it somewhere or other operations?
Thanks.

**Comment by JulienPalard** [comment]
Hi!

Yes using `turtl-backup export backup_file.json some_directory/` (in command line, and require your password).

It will extract your backup in the given directory, one note per file.

Note that a non-exported backup is safe (as it needs your password to be unciphered), also backuping with an auth token allows you to backup *without your password*, so in the situation your backup box is being compromised, one get your auth token and backup files, he's still unable to read your notes (requiring your password).

**Comment by ChandelierX** [comment]
Thanks for your detailed explanation! Now I understand how it works and differs.
While, another question. 
If I lose my server, and have to build turtl again on other server, is there some way to import notes from this backup? With your code?

**Comment by JulienPalard** [comment]
>If I lose my server, and have to build turtl again on other server, is there some way to import notes from this backup? With your code?

Naupe. It may be implemented though, but as I not tried it I do not know if it's easy or hard. I implemented this backup while using the mes.framanotes.org turtl server, not mine, so I didn't cared about this point.

You may try it, I'll gladly accept PRs' :)

**Comment by ChandelierX** [comment]
Anyway, really thank your excellent work, at least I won't worry about lose anything crucial.
As for migrate turtl server, maybe I'll use this [tutorial](https://groups.google.com/forum/#!searchin/turtl/backup$20restore%7Csort:date/turtl/_dNR0WOgkCQ/o89UqRHoAAAJ) as a workaround, before I know more about coding.
Again, thanks!
