### ISSUE TITLE
Can't decrypt backup.json

### ISSUE THREAD

**Issue by iuga2000** [JulienPalard/turtl-backup#7]
Hello,

I followed your instruction to install turtl-backup on linux manjaro

pip3 install turtl-backup

I succeeded to have a backup.json file with the command
turtl-backup backup https://api.framanotes.org backup.json

But I have an error with the command turtl-backup decrypt backup.json backup/

It doesn't recognize the "decrypt" argument.

Another question is how to lauch turtl-backup-gui ?

Thank you for your help

**Comment by iuga2000** [comment]
I solved my issue. the pip3 installation doesn't decrypt.
I uninstalled (pip3 uninstall turtl-backup) and I reinstalled it from Github repositery, uncompress the files and sudo python setup install

**Comment by JulienPalard** [comment]
Hi, thanks for reporting, I just updated the version on pypi :)
